name: Run Lua Script Daily Test

on:
  schedule:
    # 每天午夜 00:00 UTC 执行（北京时间+8）
    - cron: '16 0 * * *'
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 检出代码并引用Lua和Luarocks环境
      - name: Checkout code
        uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"
      - uses: leafo/gh-actions-luarocks@v4

      # 安装 Lua
      - name: 安装Lua依赖
        run: |
          luarocks install json-lua

      # 运行 Lua 脚本
      - name: Run Lua script
        run: |
          lua Action/CleanOldSchedule.lua
          # 配置 Git
          git config --global user.name "NeNe"
          git config --global user.email "nene@jloli.cc"

          # 检查文件修改并提交
          git add d_scheduel.json
          git commit -m "Remove old scheduel via GH Actions"
          
          # 推送修改到仓库
          git push
