name: Run Lua Script Daily Test

on:
  schedule:
    # 每天午夜 00:00 UTC 执行
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 安装 Lua
      - name: Install Lua
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3

      # 运行 Lua 脚本
      - name: Run Lua script
        run: |
          lua Action/test.lua
