name: Run Lua Script Daily Test

on:
  schedule:
    # 每天午夜 00:00 UTC 执行
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 检出代码并引用Lua和Luarocks环境
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"
      - uses: leafo/gh-actions-luarocks@v4

      # 安装 Lua
      - name: 安装Lua依赖
        run: |
          luarocks install json-lua

      # 运行 Lua 脚本
      - name: Run Lua script
        run: |
          lua Action/test.lua
